backtrace-labs/backtrace-unity

Runtime/Model/BacktraceConfiguration.cs
Hello,
Back with a reduced Pull Request with only the addition of `[CreateAssetMenu(fileName = "New Backtrace Configuration", menuName = "Backtrace/Configuration", order = 0)]` to BacktraceConfiguration for inclusion in the default UX for creating ScriptableObjects.
**Note: this removes the need to use the BacktraceMenu class to add a custom menu.**
Cheers,
J.
=> Added CreateAssetMenu to BacktraceConfiguration ScriptableObject

CHANGELOG.md, Runtime/Model/Database/BacktraceDatabaseAttachmentManager.cs
Previously, the Backtrace-Unity library tried to generate a crash image in PNG format. Because of that, the image size was unacceptable. Comparison between JPG and PNG showed that JPG size is much smaller (the same image - PNG: 376KB vs JPG: 31,6KB).
This diff changes the default image type to JPG.
https://github.com/backtrace-labs/backtrace-unity/issues/26
=> Store crash image in JPG format

CHANGELOG.md, Runtime/BacktraceClient.cs
Previously, when the developer edited `BacktraceClient` source code and added `Debug.Log` (or any other log method) between `BacktraceLogManager` initialization and `CaptureUnityMessages` method, in the worst case this will cause an exception in `BacktraceClient` source code.
This diff move `BacktraceLogManager` initialization to `CaptureUnityMessages` method. We decided to initialize manager there because `BacktraceLogManager` is a required dependency of `CaptureUnityMessages` method.
https://github.com/backtrace-labs/backtrace-unity/issues/28
=> Log manager execution order

Android/BacktraceANRWatchdog.java, CHANGELOG.md, Runtime/BacktraceClient.cs, Runtime/Native/Android/NativeClient.cs
Previously Backtrace native client initialized ANR watchdog via a static java method. This caused a problems in Android 7 `AndroidJavaException: java.lang.NoSuchMethodError: no non-static method "Lbacktrace/io/backtrace_unity_android_plugin/BacktraceANRWatchdog;.<init>()V"`
This diff changes a way how we initialize ANR watchdog - right now we will use BacktraceANRWatchdog constructor instead.
=> ANR watchdog initialization

CHANGELOG.md, README.md, Runtime/BacktraceClient.cs, Runtime/BacktraceDatabase.cs, Runtime/Model/BacktraceData.cs, Runtime/Model/BacktraceStackFrame.cs, Runtime/Model/BacktraceUnhandledException.cs, Tests/Runtime/BacktraceAttributeTests.cs, package.json
- Prevent erroneously extending backtraceClient attributes with backtraceReport attributes. 
- Removed randomly generated path to assembly from callstacks.
- Prevent client from multi initialization.
=> Version 3.1.1 - remove random path in stack trace

CHANGELOG.md, README.md, Runtime/BacktraceClient.cs, Runtime/Model/BacktraceData.cs, Runtime/Model/BacktraceResult.cs, Runtime/Model/BacktraceUnhandledException.cs, Runtime/Native/Android/NativeClient.cs, Runtime/Services/BacktraceApi.cs, Tests/Runtime/BacktraceStackTraceTests.cs, Tests/Runtime/ClientSendTests.cs, package.json
- Android stack trace parser improvements,
- Fixed Android NDK initialization when database directory doesn't exist,
- Added security section to Readme
=> Version 3.2.1

CHANGELOG.md, Runtime/BacktraceClient.cs, Runtime/BacktraceDatabase.cs, Runtime/Model/BacktraceData.cs, Runtime/Services/BacktraceApi.cs, Runtime/Types/BacktraceResultStatus.cs, package.json
=> Version 3.2.2

CHANGELOG.md, Runtime/BacktraceClient.cs, Runtime/BacktraceDatabase.cs, package.json
**Problem**
When user pause a game, `Time.time` value isn't updated by Unity engine. However, Backtrace's Unity Game object update method will be still called by Unity engine. 
Previously our ANR detection algorithm used `Time.time` value to determine game hangs. In the situation when game is paused, `Time.time` value isn't updated. To fix this issue Backrace-Unity has to use `Time.unscaledTime` to determine time elapsed since game startup that won't be stopped by game pauses.
1. Pause game
2. Check Backtrace after ~10 seconds 
3. If report is available in Backtrace it means that we were able to reproduce issue
- Pause game,
- Check if game reported ANR
**Result:** Game didn't report ANR
- Pause a game,
- start ANR,
- Check if game reported ANR 
**Result:** Game reported ANR
- Don't pause …
=> Version 3.3.2 - ANR detection fix 

CHANGELOG.md, Editor/BacktraceClientEditor.cs, Runtime/BacktraceClient.cs, package.json
- Fixed iOS compilation issue with Backtrace namespace,
- Prevents from displaying Backtrace configuration when Application.isPlaying is true to avoid user mistakes.
=> Version 3.3.3

Runtime/BacktraceClient.cs, Runtime/Native/Android/NativeClient.cs, Runtime/Native/INativeClient.cs, Runtime/Native/iOS/NativeClient.cs
When the user closed an application just after the ANR watchdog ANR check, the next time when an application goes from background to foreground, the ANR watchdog might report a false-positive ANR. To prevent this situation we need to also detect when an application goes to background/foreground and prevent/allow ANR checks depends on the application state.
* Game objects update method works only when an application is in the foreground, however, our ANR watchdog background thread is able to compare main/background thread time even when an application goes to background. In this situation when an application goes to the background just after ANR check and before any update method, we will report an ANR situation. When an application goes to foreground/background the `nativeClient` instance …
=> Detect false-positive ANRs report and prevent ANR watchdog from sending them

Runtime/BacktraceClient.cs, Runtime/Common/MathHelper.cs, Runtime/Common/MathHelper.cs.meta, Runtime/Interfaces/IBacktraceSession.cs, Runtime/Interfaces/IBacktraceSession.cs.meta, Runtime/Model/Session/EventAggregationBase.cs, Runtime/Model/Session/EventAggregationBase.cs.meta, Runtime/Model/Session/SessionEvent.cs, Runtime/Model/Session/SessionEvent.cs.meta, Runtime/Model/Session/SessionSubmissionJob.cs, Runtime/Model/Session/SessionSubmissionJob.cs.meta, Runtime/Model/Session/UniqueEvent.cs, Runtime/Model/Session/UniqueEvent.cs.meta, Runtime/Services/BacktraceSession.cs, Runtime/Services/BacktraceSession.cs.meta, Tests/Runtime/Session.meta, Tests/Runtime/Session/BacktraceSessionTests.cs, Tests/Runtime/Session/BacktraceSessionTests.cs.meta, Tests/Runtime/Session/Mocks/BacktraceHttpClientMock.cs, Tests/Runtime/Session/SessionEventTests.cs, Tests/Runtime/Session/SessionEventTests.cs.meta, Tests/Runtime/Session/UniqueEventsTests.cs, Tests/Runtime/Session/UniqueEventsTests.cs.meta
This diff shows business logic responsible for event aggregation support in the Backtrace-Unity client. 
Information for reviewers:
* BacktraceClient - class responsible for Backtrace integration in Unity - creates a single instance of BacktraceSession on application startup. Developers can't create more instances than one. BacktraceClient manage BacktraceSession class lifecycle.
*  BacktraceSession allows adding unique (hearthbeat) events and session events.
* BacktraceSession tick method will be invoked by BacktraceClient every time when Unity Engine calls the update method. In Unity, we prefer to avoid timers and this solution prevents from reserving additional resources for timers, jobs etc.
* Diffs also contains integration tests and unit tests. If you have more idea about specific …
=> Event aggregation logic for reviewers

Runtime/Native/iOS/NativeClient.cs
**Why**
Previously we assumed that structure size in the iOS is constant. Based on the feedback that we got from our customers we should be prepared for a situation when structure size is different. To achieve that we should start using IntPtr.Size - instead of assuming struct size has always the same size = 16.
=> iOS structure size change

Runtime/Native/Android/NativeClient.cs
**Why**
We detected that sometimes when the Unity Android solution is being generated by 3rd party plugin, the application context object might not be available on the application startup. In this situation, the plugin currently will throw an unhandled exception and won't initialize native integration. To prevent this situation we added an additional check for nullable application context and also added a code that still allows us to guess library path based on the most popular application setup.
=> Guess native library path when application context is not available

Runtime/Native/Android/NativeClient.cs
**Why**
In some builds, Unity player might be available under a different name or might be overall unavailable for backtrace-unity. This change allows us to use a custom function to guess the native library path and prevents backtrace-unity from throwing an exception on native-client initialization.
=> Handle different unity player java class name

Runtime/BacktraceDatabase.cs, Runtime/Interfaces/IBacktraceDatabase.cs, Runtime/Interfaces/IBacktraceDatabaseFileContext.cs, Runtime/Model/Database/BacktraceDatabaseAttachmentManager.cs, Runtime/Services/BacktraceDatabaseFileContext.cs, Tests/Runtime/Database/Mocks/BacktraceDatabaseFileContextMock.cs
As a user, I would like to define attachments settings that allow the game to save resources/time when the game generates image attachment.
As a power user, I would like to use database API to define screenshot settings.
=> Screenshot management

README.md
Support for Client Side Unwinding is provided for Android on Unity 2019+
=> Details for Client Side Unwinding Unity 2019+

Editor/BacktraceConfigurationEditor.cs
We discovered that the `EditorGUILayout.PropertyField` API that the Unity plugin uses to draw Backtrace configuration options on the UI doesn't work correctly on the old version of Unity with enum flags. By default, the user instead of selecting multiple values can select only one. 
This diff allows user to select multiple values in the backtrace-unity configuration window in the Unity 2017/2018
=> Multiselect dropdown support

Runtime/Json/BacktraceJObject.cs, Tests/Runtime/BacktraceJObjectTests.cs
We detected a problem with the control characters that the Unity plugin sends. Without control characters escaping mechanism, invalid JSON provided by Unity plugin might break web ui parser. This diff correctly escapes control characters in the plugin.
=> Escape control characters

Runtime/BacktraceClient.cs, Runtime/BacktraceDatabase.cs, Runtime/Common/ClientPathHelper.cs, Runtime/Model/BacktraceReport.cs, Runtime/Model/Database/BacktraceDatabaseRecord.cs
This diff contains safe code that we should execute when a game executes Backtrace client code outside the main thread. This code also solves problems detected while I was trying to figure our correct solution to this issue.
=> Backtrace thread API improvements

Editor/BacktraceConfigurationEditor.cs, Runtime/Extensions/EnumExtensions.cs
This change allows to print warning message when report filter is set to all so the backtrace-unity plugin will prevent from sending any report.
=> Warning message when filter report is set all All

Runtime/Model/Database/BacktraceDatabaseAttachmentManager.cs
This diff decreases the default screenshot quality generated by backtrace-unity when a user checks options to include screenshots in each backtrace-report.
=> Decrease default texture quality

Runtime/BacktraceDatabase.cs, Runtime/Model/BacktraceConfiguration.cs, Runtime/Model/BacktraceHttpClient.cs, Runtime/Model/Breadcrumbs/BacktraceBreadcrumbType.cs, Runtime/Model/Breadcrumbs/BacktraceBreadcrumbs.cs, Runtime/Model/Breadcrumbs/UnityEngineLogLevel.cs, Runtime/Model/Database/BacktraceDatabaseRecord.cs, Tests/Runtime/Breadcrumbs/BacktraceBreadcrumbsTypeTests.cs, Tests/Runtime/Breadcrumbs/BreadcrumbsLogLevelTests.cs
This diff contains small breadcrumbs initialization improvements. With these improvements, backtrace-unity will:
* disable breadcrumbs integration, when a client decides to not select any supported log level or any breadcrumb type,
* ignores files that are empty.
=> Breadcrumbs initialization improvements

CHANGELOG.md, Runtime/BacktraceClient.cs, Runtime/BacktraceDatabase.cs, Runtime/Model/Breadcrumbs/BacktraceBreadcrumbs.cs, Runtime/Model/Breadcrumbs/BacktraceBreadcrumbsEventHandler.cs, Runtime/Model/Breadcrumbs/IBacktraceBreadcrumbs.cs, Runtime/Native/Android/NativeClient.cs, Runtime/Native/Base.meta, Runtime/Native/Base/NativeClientBase.cs, Runtime/Native/Base/NativeClientBase.cs.meta, Runtime/Native/INativeClient.cs, Runtime/Native/NativeClientFactory.cs, Runtime/Native/Windows/NativeClient.cs, Runtime/Native/iOS/NativeClient.cs, Tests/Runtime/Breadcrumbs/BacktraceBreadcrumbsTypeTests.cs, Tests/Runtime/Breadcrumbs/BreadcrumbsFileOperationTests.cs, Tests/Runtime/Breadcrumbs/BreadcrumbsLogLevelTests.cs, Tests/Runtime/Native/BreadcrumbsAnrTests.cs, Tests/Runtime/Native/BreadcrumbsAnrTests.cs.meta, Tests/Runtime/Native/Mocks.meta, Tests/Runtime/Native/Mocks/TestableNativeClient.cs, Tests/Runtime/Native/Mocks/TestableNativeClient.cs.meta, Tests/Runtime/Native/Windows/ScopedNativeAttributesTests.cs
This diff adds support for breadcrumbs log when ANR occurs. This diff also abstracts some logic from each native client and changes the way how BacktraceClient can initialize breadcrumbs integration. We need to know available options before we start native integration, so this requirement required us to rethink the way how we enable/start breadcrumbs integration.
=> Breadcrumbs ANR support

Runtime/Native/iOS/NativeClient.cs
This diff updates our native binaries and disable iOS native integration on Application.Exit even in Unity.
=> Disable integration on app.exit

Runtime/Native/Android/NativeClient.cs, Runtime/Native/Windows/NativeClient.cs
This diff fixes compilation issues on specific native platforms in older .NET versions
=> Native client compilation issues in older .NET platforms

Editor/BacktraceConfigurationEditor.cs, Editor/BacktraceDatabaseConfigurationEditor.cs, Runtime/Model/BacktraceConfiguration.cs, Runtime/Model/Database/BacktraceDatabaseSettings.cs
This diff adds support for default values in the UI. Previously a user knew that when the user launched the game. Now, we gonna apply some default every time when a user sets an invalid value. This pattern reuses the Unity editor pattern for unsigned integers that are available on the UI. Since this is the public API to make sure it won't break, we didn't change the variable types.
=> Apply default when value is below limit

Android/BacktraceANRWatchdog.java, CHANGELOG.md, Editor/BacktraceConfigurationEditor.cs, Editor/BacktraceDatabaseConfigurationEditor.cs, Runtime/BacktraceClient.cs, Runtime/Model/BacktraceConfiguration.cs, Runtime/Model/BacktraceResult.cs, Runtime/Model/Database/BacktraceDatabaseSettings.cs, Runtime/Native/Android/NativeClient.cs, Runtime/Native/Base/NativeClientBase.cs, Runtime/Native/Windows/NativeClient.cs, Runtime/Native/iOS/NativeClient.cs, package.json
- Anr watchdog timeout configuration,
- .net 3.5 compilation issue fix for native client for older unity version,
- iOS native binary update to purge invalid plCrashReporter reports,
- Default options for invalid configuration properties
=> Version 3.7.1

README.md
The [link](https://backtrace.io/create-unity) to the webpage used to create a Backtrace instance returns a 404. 
Fix: This change updates the link to go to the new register page.
=> Updates link to register page

Runtime/Native/Base/NativeClientBase.cs
Avoid using Anr Watchdog timeout in native client base on not supported platforms.
=> Avoid using unsupported property in not-native builds

Android/BacktraceAndroidBackgroundUnhandledExceptionHandler.java, Runtime/BacktraceClient.cs, Runtime/Native/Android/NativeClient.cs, Runtime/Native/NativeClientFactory.cs
In the past our java background exception handler prevented from passing the background thread exception information. Right now we're doing that so other handlers can handle it.
=> Invalid background exception behavior

Runtime/Native/Android/NativeClient.cs
Prevent a situation when the "dispose" method was called twice.
=> Prevent monitor disposing in the disable method

Runtime/Model/Attributes/ProcessAttributeProvider.cs, Runtime/Model/Attributes/RuntimeAttributeProvider.cs
This diff moves attributes that might change over the time from scoped attributes loaded only once on the runtime startup to dynamic attributes loaded every time when Backtrace is going to create a report.
=> Unity dynamic attributes

Editor/BacktraceConfigurationEditor.cs, Runtime/BacktraceClient.cs, Runtime/Model/BacktraceConfiguration.cs, Runtime/Native/iOS/NativeClient.cs, package.json
A simple change that adds the "Enable client side unwinding" checkbox, available on Android, to iOS builds.
At this moment, the option is passed to the `NativeClient`'s `Start` method, but we need to wait for a native implementation of this feature.
=> Adds a checkbox for iOS builds to enable client side unwinding.

Runtime/Model/Attributes/RuntimeAttributeProvider.cs
This diff adds `application.package` attribute to list of default backtrace-unity attributes. The attribute will be now available on every type of report
=> Package attribute

CHANGELOG.md, Runtime/BacktraceClient.cs, Runtime/Model/Attributes/RuntimeAttributeProvider.cs, package.json
This diff contains changelog/library version updates.
Goal: move from preview to general availability
Focus on: native functionality due to library updates
Test binary:
[BacktraceTestProject 3.zip](https://github.com/backtrace-labs/backtrace-unity/files/9376895/BacktraceTestProject.3.zip)
Test devices:
No screenshots captured.
=> Release 3.7.7

Runtime/Model/BacktraceUnhandledException.cs, Tests/Runtime/BacktraceStackTraceTests.cs
By default, if the stack trace algorithm cannot find a correct way to determine the OS, the algorithm uses "Android" parser to parse the stack frame. This diff changes the behavior of the stack trace parser. Now we're guessing if we can use "android" parser and depends on the if def condition
=> Fix inalid stack frame type

Runtime/Model/BacktraceUnhandledException.cs, Tests/Runtime/BacktraceStackTraceTests.cs
In the past Backtrace-Unity did generate an empty library name if the source code information was empty OR provided pre-generated information like `<123123123: 0>` - no information about source code. 
Right now, backtrace-unity plugin will try to determine the library name based on the namespace
=> Determine library name based on the namespace/function name

Runtime/Services/BacktraceMetrics.cs
This diff allows using of user-specific unique event attributes instead of using the default provided by the library
=> Unique event default attribute name

Runtime/BacktraceDatabase.cs
- Bug: FlushRecord not starting stopwatch.
- Removed unecessary allocation of stopwatch when unused.
Edit (removed point):
- Removed excessive allocation of enumerators and loops over attachments enumerable in Add
=> Bug fix and performance improvement

CHANGELOG.md
This diff updates the native library with removed duplicated identifier. 
refs BT-728
=> iOS duplicated identifier

Runtime/Model/Attributes/MachineAttributeProvider.cs, Runtime/Native/Android/NativeClient.cs
Unity-specific attributes we were populating in unity were including kernel version rather than system version. Because of that, our users couldn't check what version of the OS is impacted.
This diff includes OS version now as an attribute
=> Attributes normalization

CHANGELOG.md, Editor/Native/Android/SymbolsUpload.cs, Runtime/Model/BacktraceData.cs, Runtime/Model/JsonData/Annotations.cs
This diff fixes the symbols archive - because of recent changes the command line tool we used to archive/modify symbols is not available. Now we're using pure C# API to do such a thing.
=> Use C# api to upload symbols

Runtime/Model/Metrics/MetricsSubmissionQueue.cs
The list of pending jobs was being traversed using an index that was unconditionally incremented, even after removing an item from the list. This could cause a job to be skipped in `SendPendingEvents`, at least until the next frame.
This was not a fatal error as any skipped jobs would be handled in the later calls to SendPendingEvents (next tick).
Noticed while auditing the code for a reported issue with dropped events.
=> metrics: fix for pending jobs being delayed one or more frames

Runtime/Model/Metrics/MetricsSubmissionQueue.cs
Previously, only a subset protocol errors would be considered for retry when submitting metrics (summed or unique) to events.backtrace.io. This excluded, notably, a failure to connect to the server at all. If the device was offline at startup, for instance, then the "Application Launches" event would never get sent.
This commit changes the handling so that any network error will also go through the retry logic for submitting an event.
=> metrics: retry submission on connection failure

Runtime/Model/Attributes/MachineAttributeProvider.cs
Last patch, we moved attributes generation outside the native client. The native client code was guarded, to be sure we won't execute the code in the editor, however `MachineAttributeProvider` isn't. This diff guards android/ios specific code to be only executed on iOS/Android 
refs: BT-1031
=> Editor guard - do not use native code in editor

Runtime/Native/XBOX/NativeClient.cs
Uses the updated API of backtrace_native_xbox.dll, previously backtrace_native_xbox_mt.dll, to specify a path for writing dump files. Prior to this commit, it was unpredictable as to whether a minidump could be written or not as the current directory of the process was (unintentionally) being used.
With this change, minidumps are written to the value specified by the configuration's database path is passed which, by default, is `Application.persistentDataPath`.
Removed unused exports, BacktraceCrash, used only for debugging, and BacktraceSetUrl, which was folded into BacktraceNativeXboxInit.
The change will require updating to the latest backtrace_native_xbox.dll.
[Internal Ref BT-509]
=> xbox native client: fixes output directory for minidumps

Runtime/Model/Attributes/RuntimeAttributeProvider.cs, Runtime/Native/XBOX/NativeClient.cs
In the xbox native client implementation, we have found a few places that require adjustments. This code makes sure:
- the error.type attribute is set like in every other native client implementation
- attributes are set only when the client is enabled,
- the integration is starting when the database directory exists.
=> Xbox native client improvements

package.json
The package actually needs the screen capture module to be present and while that is included in manifest.json by default, it can be removed
=> Added the screencapture module as a dependency

Android/BacktraceAndroidBackgroundUnhandledExceptionHandler.java
We want to be sure, all error types received in the unhandled exception handler will be reported to Backtrace. This diff makes sure, that every time we get an error in the Android unhandled exception handler, it will be converted into a backtrace report and stored to be sent 
refs BT-1964
refs BT-779
=> Report all throwable types, no matter if throwable is type error or not

Runtime/Attributes.meta, Runtime/Attributes/NotSupportedAttribute.cs, Runtime/Attributes/NotSupportedAttribute.cs.meta, Runtime/Model/BacktraceConfiguration.cs, Tests/Runtime/BacktraceClientTests.cs
The configuration object created by a user to create `BacktraceClient` requires properties available only in specific OSes. When the user needs to switch between different OS builds, most of the time it requires wrapping the initialization object with the #ifdef which is not a great user experience. 
The current change allows to define all properties in the backtrace configuration object. Not supported properties on specific OS will be marked as unsupported via NotSupported attribute. 
ref: BT-535
=> Allow defining not supported variables

Runtime/Model/Breadcrumbs/BacktraceBreadcrumbs.cs, Runtime/Model/Breadcrumbs/BacktraceBreadcrumbsEventHandler.cs, Runtime/Model/Breadcrumbs/IBacktraceBreadcrumbs.cs, Tests/Runtime/Breadcrumbs/BacktraceBreadcrumbsTypeTests.cs
This diff allows to expose one more method via Breadcrumb interface that allows to define breadcrumb level.
refs BT-2749
=> Extend breadcrumbs interface with new method that allows to define breadcrumb level

Android/BacktraceAndroidBackgroundUnhandledExceptionHandler.java
This diff allows to wait until Unity layer captures unhandled java exception captured via `BacktraceAndroidBackgroundUnhandledExceptionHandler`
=> Allow unity to finish capturing uncaught exception

Android/BacktraceAndroidBackgroundUnhandledExceptionHandler.java, Runtime/BacktraceClient.cs, Runtime/Model/BacktraceData.cs, Runtime/Model/BacktraceReport.cs
This pull request adds support for Proguard to the `BacktraceClient`. By using our new proguard symbolication API our customers can set symbolication id for their proguard maps.
ref: BT-2975
=> Proguard support

CHANGELOG.md, Runtime/BacktraceClient.cs, package.json
This pull request releases a new backtrace-unity package in version 3.9.0.
=> Release 3.9.0

Runtime/Model/Breadcrumbs/Storage/BacktraceStorageLogManager.cs
One customer shared with us a potentially bad situation that happened in the BacktraceStorageLogManager implementation - it looks like we ran outside _logSize array. Normally it cannot happen, however, we want to be sure, that even if we have a bug, the code works correctly. 
This simple patch makes sure we don't run outside _logSize array
=> Make sure we never check values outside _logSize queue

Runtime/BacktraceClient.cs, Runtime/Model/BacktraceUnhandledException.cs, Tests/Runtime/BacktraceStackTraceTests.cs
Unity uncaught exception handler can also capture unhandled exceptions thrown by the managed Java code. The following code in the java managed layer can be captured by Unity exception handler:
```
throw new RuntimeException("Unity-test: Uncaught JVM exception");
```
In this flow we didn't apply proguard symbolication. This patch makes sure the symbolication flow is applied in the unity uncaught exception handler. 
ref: BT-2993
=> Unity unhandled exception proguard flow

CHANGELOG.md, Runtime/BacktraceClient.cs, Runtime/Model/BacktraceUnhandledException.cs, Runtime/Model/Breadcrumbs/Storage/BacktraceStorageLogManager.cs, Tests/Runtime/BacktraceStackTraceTests.cs, package.json
This pull request updates our iOS native binaries. This change includes:
- PlCrashReporter update from 1.7.2 to the latest one - 1.11.2.
- Storing client attributes in the PlCrashReporter crashData object. 
- Renaming process.vm.* attributes to vm.* 
- Include detailed error message in iOS crash report
=> iOS native bindings update

Android/BacktraceCrashHandler.java.meta
These errors are being logged to the Unity console because of a broken meta file:
```
Tried to get mapping information from scalar node
Assertion failed on expression: 'IsMapping()'
```
=> Fix Unity console errors caused by corrupt meta

Runtime/BacktraceDatabase.cs, Runtime/Model/Breadcrumbs/BacktraceBreadcrumbs.cs, Runtime/Model/Breadcrumbs/BacktraceBreadcrumbsEventHandler.cs, Runtime/Model/Breadcrumbs/IBacktraceBreadcrumbs.cs
We're checking internet connection availability too often. We can check it every 30 seconds instead. To remove additional checks and some time-consuming code, the internet connection availability will be checked every 30 seconds now.
ref: BT-3079
=> Internet availability checks

Runtime/Native/Windows/NativeClient.cs
Minor change: after sending a Windows ANR hang report, make sure the next native crash isn't also treated as a hang.
I've not been able to verify that this works, but it certainly looks right and matches the intent of the comment above it! I think this was just a typo.
=> Fix error type attribute being set to hang for next error after a hang

Runtime/Interfaces/IBacktraceMetrics.cs, Runtime/Services/BacktraceMetrics.cs
This is the follow-up pull request that should fix the problem shown in the pull request: https://github.com/backtrace-labs/backtrace-unity/pull/232
=> Expose Session Id via Backtrace Metrics

Runtime/Interfaces/IBacktraceMetrics.cs, Runtime/Services/BacktraceApi.cs
This pull request changes the documentation URL to docs.saucelabs.com
ref: BT-5445
=> Change documentation url to docs.saucelabs.com

Runtime/Native/Windows/NativeClient.cs
Log a warning instead of allowing an unhandled exception to escape, if the Backtrace/Crashpad DLLs can't be found, or loaded.
This can happen if e.g. the system doesn't have the version of the VC runtime installed which is required to use these DLLs.
=> Handle missing Backtrace/Crashpad DLLs gracefully

README_ja_JP.md
This pull request fixed the jp documentation and links to the symbolication overview there.
=> Use saucelabs docs instead of the legacy docs

Runtime/Model/DataProvider/IMachineIdentifierProvider.cs.meta, Runtime/Model/DataProvider/ISessionStorageDataProvider.cs.meta, Runtime/Model/DataProvider/NetworkIdentifierProvider.cs.meta, Runtime/Model/DataProvider/SessionStorageDataProvider.cs.meta, Runtime/Model/DataProvider/UnityMachineIdentifierProvider.cs.meta
The new unique id provider was developed on Windows. Somehow, the Unity editor there didn't add proper metadata annotations. This pull request extends the default Unity metadata generated by the Unity Editor on Mac
=> Add data providers metadata

Android/lib/arm64-v8a/libbacktrace-native.so.meta, Android/lib/arm64-v8a/libnative-lib.so.meta, Android/lib/armeabi-v7a/libbacktrace-native.so.meta, Android/lib/armeabi-v7a/libnative-lib.so.meta, Android/lib/x86/libbacktrace-native.so.meta, Android/lib/x86/libnative-lib.so.meta, Android/lib/x86_64/libbacktrace-native.so.meta, Android/lib/x86_64/libnative-lib.so.meta
Some Unity Editors raise a warning about "Is16KbAligned" when it's not included in the metadata files, This PR restores 'Is16KbAligned' flag.
ref: BT-6078
=> Restore .meta 'Is16KbAligned' flag
